[Icon Theme]
Name=Breeze PLaSK
Comment=Elegant monochromatic icon theme
Inherits=breeze
Hidden=true

Directories=scalable

[scalable/actions]
Size=48
Context=Actions
Type=Scalable
MinSize=16
MaxSize=256

[scalable/places]
Size=48
Context=Places
Type=Scalable
MinSize=16
MaxSize=256

[scalable/apps]
Size=48
Context=Applications
Type=Scalable
MinSize=16
MaxSize=256

[scalable/mimetypes]
Size=48
Context=MimeTypes
Type=Scalable
MinSize=16
MaxSize=256
